apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mlp-api-ingress
  namespace: mlp-dev
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: api.mlp.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mlp-api
                port:
                  number: 80
