# syntax=docker/dockerfile:1

FROM prom/prometheus:v3.14.0

WORKDIR /etc/prometheus

COPY --chown=nobody:nobody monitoring/prometheus/prometheus.yml /etc/prometheus/prometheus.yml
COPY --chown=nobody:nobody monitoring/prometheus/rules/ /etc/prometheus/rules/

EXPOSE 9090
